# UAV is limited to 7 m/s
max_velocity: 7.0 # [m/s]

# UAV is limited to 2.5 m/s
max_acceleration: 2.5 # [m/s^2]

turning_velocity: 2.5 # [m/s]
plot: false

problem: "../../mtsp_problem_loader/problems/random_problem0.tsp"

